calificaciones = [1,2,3,4,5]
nombres = ["moises","camila","fernanda","pablo","tania"]
lista_variada = [True, 10.5, "abc", [0,1,1]]

print("estudiate:", nombres[2])
print("calificacion:", calificaciones[-2])
print("lista dentro de otra ", lista_variada[3][0])
print("imprimir un rango o slices",nombres[1:2])
print(lista_variada)

#agregar elementos a una lista
nombres.append("anibal")
print(nombres)
